import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import TransitionProvider from "@/components/TransitionProvider";

export const metadata: Metadata = {
  title: "Mail Tym",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`bg-black h-screen`}>
        <TransitionProvider>{children}</TransitionProvider>
        </body>
    </html>
  );
}
